### PR TITLE
Add Wireshark decoder

### PR DESCRIPTION
**Pull request by magicrub**
This adds a Wireshark decoder for easier parsing of packet inspection.
Features:
- includes a HOWTO for installation and use
- added a gitignore for a auto-generated traces file in case someone runs a capture from from here
- DEBUG_STRING content is shown in the packet line
- Many variables are translated but there's plenty more that need to be converted from network layer units to human-readable units
- If a packet has zero length, the description says "FETCH" for easier browsing (you don't have to open up the packet to realize there's nothing in it)
- you can filter the whole capture easily with "trillium" and other fields like "trillium.Size>0" and/or "trillium.msg_id==177" or to exclude them with "!(trillium.msg_id==212)". See pictures.
- can decode multiple Orion packets in a single IP packet

Pictures!
image

image

image

image

### CODE REVIEW

**Comment by magicrub** [comment]
ping @jefffisher Please take a look if this is something Trillium is interested in or not.

**Comment by magicrub** [comment]
ping @aaronjaques Please take a look if this is something Trillium is interested in or not.

**Comment by jefffisher** [comment]
Hi @magicrub – this looks nice, and much simpler to maintain than Orion-Wireshark.lua, but I haven't had a chance to review yet. This repo is just a mirror of a subtree of our internal SVN repo, but I will add it internally and eventually it will show up once I've had a chance to review, get it committed, and sync it to github.

**Comment by magicrub** [comment]
@jefffisher thanks, Yeah, I noticed it was an SVN mirror. You guys should internally switch over to git full-time and mirror that to SVN if you need it :)

**Comment by jefffisher** [comment]
@magicrub I'm actually not opposed; unfortunately, git is not able to handle one of our (admittedly funky) use cases at all, so we're pretty much stuck for the time being...

**Comment by magicrub** [comment]
> git is not able to handle one of our (admittedly funky) use cases at all

Oh.. I'm intrigued!

**Comment by jefffisher** [comment]
Added in 4c68583. @magicrub note that I put it in a slightly differently named directory and lumped my existing lua parser in there as well

**Pull request closed without merging**
